<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kuestenlogik.Akka.Surgewave.Streams\Kuestenlogik.Akka.Surgewave.Streams.csproj" />
    <PackageReference Include="Kuestenlogik.Surgewave.Runtime" />
  </ItemGroup>

</Project>
